"""
Test fixtures containing realistic FNOL (First Notice of Loss) document text.
These simulate the text extracted from various incoming claim documents.
"""

FIXTURE_FAST_TRACK = """
My name is John Smith and I am reporting an incident that occurred on 2024-03-15 under my policy number POL-789456. The claim number assigned to me previously, or for reference, is CLM-2024-001. I was involved in a minor rear-end collision while stopped at a red traffic signal. Thankfully, there were absolutely no injuries sustained by myself or the other party involved. My vehicle, however, has sustained noticeable bumper damage which will need to be repaired. I am filing this as a vehicle claim since only property damage occurred. The estimated damage for the repairs currently stands at approximately $12000. For any follow-up questions, please reach out to me via my contact phone at 555-0101. Alternatively, you can always send correspondence to my contact email, which is john.smith@email.com. The police did arrive at the scene to document the event, and the official police report number is PR-2024-445.
"""

FIXTURE_SPECIALIST_QUEUE = """
I am Sarah Jenkins and I need to file an injury claim regarding an accident that took place on 2024-03-20. My active insurance policy number is POL-987654. For tracking purposes, please use the claim number CLM-2024-002. I was at a complete stop in heavy traffic when another driver collided forcefully with the rear of my car. Because of the sudden impact, I suffered severe whiplash and have been experiencing significant neck pain. I am currently seeking ongoing medical treatment and physical therapy for these injuries. My vehicle was heavily damaged, but my main concern is the medical expenses related to this event. Based on initial medical bills and mechanic quotes, the estimated damage is currently around $45000. You can reach me by calling my contact phone at 555-0202 or sending a message to my contact email at sarah.jenkins@email.com. The authorities were notified, and the police report number for this distressing incident is PR-2024-450.
"""

FIXTURE_INVESTIGATION_FLAG = """
This is Michael Brown reporting a vehicle incident that happened late at night on 2024-04-01 under policy number POL-112233. The reference claim number I was given is CLM-2024-003. I was driving down a deserted industrial road when a car suddenly pulled out of an alley and side-swiped me. To be honest, the whole sequence of events felt incredibly staged by the other driver. They immediately demanded cash at the scene before even checking for any real damage. I declined and insisted on going through the proper insurance channels, though they seemed unusually prepared for a collision. Despite it looking like a simple scrape, the shop gave me a ridiculously high quote, bringing the estimated damage to $80000. Please contact me on my phone at 555-0303 or email me at michael.brown@email.com if you need more details. The police were reluctant to come out for a non-injury accident but eventually gave me police report number PR-2024-460. I highly recommend an adjuster look closely at the other driver's statement before proceeding.
"""

FIXTURE_MANUAL_REVIEW = """
Hello, my name is Emily Davis and I am submitting this vehicle claim documentation for a recent accident. Unfortunately, I cannot locate my policy documents right now, so I have left the policy number blank. I also do not recall the exact incident date as it was a few days ago in a blur of confusion. The claim number allocated to this file is CLM-2024-004. I collided with a parked car while navigating a very tight parking structure downtown. Fortunately, there were no injuries involved, but both cars suffered moderate body damage along the side panels. The auto body shop informed me that the estimated damage will be roughly $30000 to fix both vehicles properly. I would appreciate it if someone could call me at my contact phone, 555-0404, or email me at emily.davis@email.com to help me track down my policy details. I have a police report to submit as well, with the police report number being PR-2024-470. Thank you for your assistance in processing this incomplete submission and guiding me on the next steps.
"""
